Code to pull and clean up data
Tentative plan is to pull the dataset below:
https://github.com/owid/co2-data
and clean it up for analysis.

In [1]:
# imports
import os
import pandas as pd

In [2]:
# Load and cache dataset from URL if not already cached
dataset_name = "owid-co2-data"

url = "https://github.com/owid/co2-data/raw/refs/heads/master/owid-co2-data.csv"
FOLDER = "../data"
LOCAL_PATH = f"{FOLDER}/{dataset_name}.csv"

raw_df = pd.DataFrame()
if os.path.exists(LOCAL_PATH):
   raw_df = pd.read_csv(LOCAL_PATH)

else:
    raw_df = pd.read_csv(url)
    os.makedirs(os.path.dirname(FOLDER), exist_ok=True)
    raw_df.to_csv(LOCAL_PATH, index=False)

print(f"{raw_df.shape}")

(50411, 79)

In [3]:
# Looking at the dataframe

# raw_df.info()
raw_df.describe()

,year,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
count,50411.000000,4.116700e+04,1.525100e+04,29173.000000,25648.000000,29384.000000,27216.000000,26239.000000,23796.000000,23496.000000,...,2170.000000,41238.000000,38280.000000,41238.000000,41238.000000,38280.000000,38150.000000,37813.000000,4712.000000,4712.000000
mean,1920.349249,6.017294e+07,3.300495e+11,7.890109,0.060026,420.227035,6.268847,42.598225,544.144592,7.483698,...,7.190616,2.272236,0.002871,0.008014,0.011224,0.000509,490.799608,310.521459,-6.986781,21.468641
std,65.859123,3.308412e+08,3.086383e+12,62.988171,0.123566,1972.092032,62.199548,1721.913018,2273.281696,99.512520,...,17.448980,9.282343,0.015362,0.045687,0.062888,0.003048,2414.076755,1812.363570,259.018184,62.637598
min,1750.000000,2.150000e+02,4.998000e+07,0.000000,0.000000,0.000000,-1928.339000,-100.000000,-84.560000,-2298.978000,...,0.000000,-0.824000,-0.001000,-0.000000,-0.001000,0.000000,-19.725000,0.000000,-2177.807000,-98.281000
25%,1875.000000,3.272140e+05,7.874038e+09,0.000000,0.000000,0.381000,-0.005000,-1.070500,6.667750,-0.727500,...,0.144000,0.003000,0.000000,0.000000,0.000000,0.000000,1.502000,0.221000,-2.262250,-6.828750
50%,1925.000000,2.291264e+06,2.743861e+10,0.000000,0.001000,5.081000,0.044000,3.813000,28.120000,0.112000,...,0.588500,0.081000,0.000000,0.000000,0.000000,0.000000,14.605500,2.222000,1.641000,8.381500
75%,1975.000000,9.986553e+06,1.212627e+11,0.524000,0.077000,53.656500,1.018000,10.884000,124.303250,2.765250,...,2.416500,0.373000,0.000000,0.001000,0.002000,0.000000,76.508500,27.863000,11.425500,32.782250
max,2024.000000,8.161973e+09,1.301126e+14,1666.885000,2.484000,38598.578000,1804.657000,180870.000000,43184.086000,2614.874000,...,100.000000,100.000000,0.377000,1.216000,1.678000,0.085000,54433.398000,43714.777000,1768.846000,1023.042000

In [4]:
# Limiting dataset to North America only and starting from 1990
NA_countries = ['Canada', 'United States', 'Mexico']
NA_df = raw_df[raw_df['country'].isin(NA_countries)]
# NA_df = NA_df[NA_df['year'] >= 2010]

NA_df.describe()

,year,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
count,640.000000,6.260000e+02,4.920000e+02,419.000000,419.000000,634.000000,631.000000,631.000000,519.000000,516.000000,...,70.000000,522.000000,522.000000,522.000000,522.000000,522.000000,525.000000,525.000000,102.000000,102.000000
mean,1916.023438,5.924176e+07,1.798427e+12,10.093453,0.091854,776.855785,9.347355,7.615968,1295.934143,10.103849,...,19.031357,9.163621,0.007199,0.034011,0.042724,0.001400,1491.326482,1089.381949,105.329392,6.971480
std,64.522984,8.093979e+07,3.744807e+12,12.828653,0.072732,1517.857035,74.732784,32.238597,1672.387608,98.439649,...,18.698087,10.644508,0.011468,0.056961,0.070700,0.002563,2007.755440,1846.551559,150.424648,6.663613
min,1785.000000,5.000000e+05,1.175856e+09,0.000000,0.000000,0.004000,-545.958000,-71.601000,19.635000,-557.476000,...,0.491000,0.539000,0.000000,0.000000,0.000000,0.000000,24.925000,2.015000,-102.032000,-5.158000
25%,1864.750000,8.963361e+06,5.694484e+10,0.346500,0.011000,1.784500,0.000000,0.000000,145.316500,-6.318750,...,0.811000,1.059000,0.000000,0.002000,0.003000,0.000000,149.465000,33.495000,16.673000,2.815250
50%,1918.000000,2.172329e+07,3.640612e+11,4.995000,0.099000,80.198000,0.553000,3.470000,526.796000,2.856000,...,15.660500,2.545500,0.002000,0.009000,0.011500,0.000000,633.490000,228.097000,49.200000,5.962500
75%,1971.000000,8.045334e+07,1.372843e+12,14.513000,0.152500,494.385250,11.215500,9.646500,1942.661000,22.674750,...,37.814500,21.999250,0.006000,0.029000,0.036000,0.001000,1991.218000,679.156000,105.979750,10.410500
max,2024.000000,3.454266e+08,1.949317e+13,46.851000,0.241000,6126.903000,463.021000,600.000000,6450.404000,619.222000,...,46.556000,27.896000,0.039000,0.247000,0.296000,0.011000,7428.800000,6806.651000,573.595000,23.287000